### PR TITLE
Update image links README.md

### PR DESCRIPTION
**Pull request by kaushalpowar**
Updated not working images links.
Tried updating logo.png but the image is not visible. 
Left-aligned logo.png can be visible, but the centre-align image in not visible.

### CODE REVIEW

**Comment by davidmezzetti** [comment]
Hello, thanks for submitting a PR.

Can you please explain what's broken? The current images all show for me in the README. The gh-light-mode-only/gh-dark-mode-only qualifiers are important so the README on GitHub doesn't show both images.

**Comment by kaushalpowar** [comment]
Hello @davidmezzetti 
The images are not visible in my Chrome browser. I rechecked in Safari as well.
Here have a look.
Screenshot 2023-01-05 at 10 00 01 PM

I'll make a new pull request with gh-light-mode-only/gh-dark-mode-only qualifiers (I was not aware of them).

**Comment by davidmezzetti** [comment]
I can see them fine in all desktop and mobile browsers I have. Is it possible you have some sort of browser extension that is blocking them?

**Comment by kaushalpowar** [comment]
My GitHub android app is also not showing images. I will look if there's some issue from my side. Thank you for letting me know.

**Comment by davidmezzetti** [comment]
I'm going to go ahead and close this for now given the current URLs are all valid/resolvable. Feel free to provide more info if you're able.

**Pull request closed without merging**
