### PR TITLE
add multi-label clasification

### PR DESCRIPTION
**Pull request by abdullahtarek**
This branch adds one more type of trainer. This is the multi-label classification model. The edits are minor, but it was useful for me to train a multi_label classifier with txtai. I really appreciate txtai, let me know if you request any edits. Thanks

### CODE REVIEW

**Comment by davidmezzetti** [comment]
Hi @abdullahtarek, thank you for the PR! 

I think this change is a good one. I wonder if it can be fulfilled without adding a new category though. For example, I'm not sure the problem_type needs to be set in the config. Did you try just the data package change? As a side note, there is a typo in the category name `multi-lable-text-classification`.

The tests also are failing with this change as of now. I would also look to add a couple tests for this new use case for test coverage. 

Thank you!

**Comment by abdullahtarek** [comment]
hello @davidmezzetti, Thanks a lot for the reply. This is a great suggestion, I will add the multi-class classification without a different problem type. We can detect it from the labels themselves.  Also, I will try to make the tests work. I will be submitting another pull request in the upcoming days. Thanks, @davidmezzetti . Let me know if there is anything else I can do before submitting it.

**Comment by abdullahtarek** [comment]
@davidmezzetti Sorry I was stuck with work in the last couple of days. I will start working on the edits within this week. Thanks for your patience.

**Comment by davidmezzetti** [comment]
Hi @abdullahtarek - just wanted to check in on this and see if work is still planned. Otherwise, I was going to go ahead and close this PR. Thank you.

**Comment by abdullahtarek** [comment]
Hello @davidmezzetti , Sorry I got super busy with some exam preparations. You can close this PR and I can open another PR after the exams are done if this was not implemented still. 

Thanks a lot @davidmezzetti . I really Appreciate all the work you put in this repo.

**Comment by davidmezzetti** [comment]
No problem, I appreciate the response!

**Pull request closed without merging**
