### PR TITLE
Create README-Korean.md

### PR DESCRIPTION
**Pull request by 0206pdh**
README-Korean.md is README.md file translated into Korean.
If there are any mistakes or requirements in this pull request process, please let me know. I'll fix it as soon as possible.
Thank you!!

### CODE REVIEW

**Comment by davidmezzetti** [comment]
Thank you, I appreciate you putting the time into this.

Can you rename the file to README_ko.md?

**Comment by 0206pdh** [comment]
Sure! I changed the name of README.md file translated into Korean according to your request. Please check it again.

**Comment by davidmezzetti** [comment]
Thank you for this pull request! Going to merge it in now. Since I don't speak Korean, I won't be able to maintain the file but if you want to periodically check in and update it, that would be great!

**Comment by davidmezzetti** [comment]
Closes #138

**Pull request merged**
